# Generated by Django 5.0.4 on 2024-04-25 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_alter_category_name_product_sale_detailsale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 25, 19, 33, 55, 54794, tzinfo=datetime.timezone.utc), null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 25, 19, 33, 55, 55794, tzinfo=datetime.timezone.utc), null=True, verbose_name='Date Joined'),
        ),
    ]
