# Generated by Django 5.0.4 on 2024-04-29 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_birth_date_alter_sale_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 29, 21, 11, 43, 771399, tzinfo=datetime.timezone.utc), null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 29, 21, 11, 43, 771399, tzinfo=datetime.timezone.utc), null=True, verbose_name='Date Joined'),
        ),
    ]
