# Generated by Django 5.0.4 on 2024-04-29 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_description_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 29, 21, 12, 1, 270268, tzinfo=datetime.timezone.utc), null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 29, 21, 12, 1, 270268, tzinfo=datetime.timezone.utc), null=True, verbose_name='Date Joined'),
        ),
    ]
