# Generated by Django 5.0.4 on 2024-04-30 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_birth_date_alter_sale_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 30, 15, 0, 2, 638995, tzinfo=datetime.timezone.utc), null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 30, 15, 0, 2, 639998, tzinfo=datetime.timezone.utc), null=True, verbose_name='Date Joined'),
        ),
    ]
