# Generated by Django 5.0.4 on 2024-04-30 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_category_name_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 30, 17, 13, 17, 471827, tzinfo=datetime.timezone.utc), null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 30, 17, 13, 17, 471827, tzinfo=datetime.timezone.utc), null=True, verbose_name='Date Joined'),
        ),
    ]
